name: UI Alignment and Visual Regression

on:
  pull_request:
    branches: [main]

jobs:
  ui-regression:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate lockfile if missing
        run: |
          if [ ! -f package-lock.json ]; then
            npm install --package-lock-only
          fi

      - name: Install dependencies
        run: npm ci

      - name: Run DOM structure and CSS validation tests
        run: |
          npm run test:structure
          npm run test:css

      - name: Start static server
        run: |
          npx serve -l 3000 . &
          echo $! > server.pid

      - name: Wait for server
        run: npx wait-on http://127.0.0.1:3000

      - name: Run Puppeteer alignment tests
        env:
          TEST_BASE_URL: http://127.0.0.1:3000
        run: npm run test:alignment

      - name: Run visual regression tests
        env:
          TEST_BASE_URL: http://127.0.0.1:3000
        run: npm run test:visual

      - name: Stop server
        if: always()
        run: |
          if [ -f server.pid ]; then
            kill $(cat server.pid)
          fi
